POST http://localhost:8081/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="loop.jpg"

< C:\Users\Java_Back_End\Desktop\HOMEWORK\loop.jpg


### video
POST http://localhost:8081/api/v1/attach/public/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1.mp4"

< C:\Users\Java_Back_End\Desktop\HOMEWORK\1.mp4


### open general
GET http://localhost:8081/api/v1/attach/public/open_general/89fd1bc8-9760-468c-a8d9-ec7cffedfa9b.mp4


### download
GET http://localhost:8081/api/v1/attach/public/download/89fd1bc8-9760-468c-a8d9-ec7cffedfa9b.mp4

### pagination attach
PUT localhost:8081/api/v1/attach/adm/paging
Authorization: Beare eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMxMTQ0MDMsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMyMDA4MDMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.VKJN4tymkeuJaSX_WvuUVxWkSKLmnpaxtUKBXffb0ET-eHpQKYp3qIsTKkDUNwpx28O3hvazqBI8Hdjg0JXeow


### pagination attach
GET localhost:8081/api/v1/attach/delete/ff4687a3-a764-4d6f-a3a6-10a7f2bd2074
Authorization: Beare eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMxMTQ0MDMsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMyMDA4MDMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.VKJN4tymkeuJaSX_WvuUVxWkSKLmnpaxtUKBXffb0ET-eHpQKYp3qIsTKkDUNwpx28O3hvazqBI8Hdjg0JXeow