### Create channel
POST localhost:8081/api/v1/channel/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQyMzQ5MTgsImVtYWlsIjoiQWxpeWV2VmFsaUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0MzIxMzE4LCJpc3MiOiJ5b3V0dWJlIHRlc3QgcG9ydGFsaSJ9.OWEmJ1qoxMwW8lHUeQ34-Y5SOvnBGbaYPX0xbW4rKPYyuLoc8oQDZigPMb5GUHfYV66BzJtLeBsgeyT2OyF89w
Content-Type:  application/json

{
  "name": "Code_Uz",
  "description": "Best Channel"
}