### Create profle
POST localhost:8081/api/v1/profile/adm-moder/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQyMzEyMjUsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjg0MzE3NjI1LCJpc3MiOiJ5b3V0dWJlIHRlc3QgcG9ydGFsaSJ9.72xiqKZ_iyWy7uAlhVn70nxdPHDc_KPKbjLisGYNDS3Vkmkfh5UwwH3LBQIgUl7fkBOny_sB8uaoZC90pi6_Sw
Content-Type:  application/json

{
  "name": "Alisher",
  "surname": "Valiyev",
  "password": "202020",
  "email": "AliyevVali@gmail.com"
}
### change paswword
POST localhost:8081/profile/change
Content-Type: application/json

{
  "oldPassword": "88888",
  "newPassword": "99999"
}