### Create profle
POST localhost:8081/api/v1/profile/adm-moder/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQyNDc0ODIsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjg0MzMzODgzLCJpc3MiOiJ5b3V0dWJlIHRlc3QgcG9ydGFsaSJ9.O_U45Znho5qtlQXV8N8tqpTNteid0O8uGEWqnjHF3avgQORx2CEotUa5jguS17uzkTkwMn_91nJaygYWtovBfg
Content-Type:  application/json

{
  "name": "Alisher",
  "surname": "Valiyev",
  "password": "202020",
  "email": "AliyevVali@gmail.com"
}
### change paswword
POST localhost:8081/api/v1/profile/changePassword
Content-Type: application/json

{
  "oldPassword": "88888",
  "newPassword": "99999"
}

### update profile detail
PUT localhost:8080/api/v1/profile/update
Content-Type: application/json

{
  "name": "Dakejon",
  "surname": "Nurlanovic"
}