### Create profle
POST localhost:8081/api/v1/profile/adm-moder/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ0MDk5MTYsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjg0NDk2MzE2LCJpc3MiOiJ5b3V0dWJlIHRlc3QgcG9ydGFsaSJ9.RLVCsFL79Ms6PK_ktYgwCmbAHsr2uhGzN4AXRcOduUw3jNYqat8AXiZJI563XZ7tttPfJXvGurpJIvH9KjIkXg
Content-Type:  application/json

{
  "name": "Ali",
  "surname": "Vali",
  "password": "2020",
  "email": "Vali@gmail.com"
}
### change paswword
POST localhost:8081/api/v1/profile/changePassword
Content-Type: application/json

{
  "oldPassword": "88888",
  "newPassword": "99999"
}

### update profile detail
PUT localhost:8080/api/v1/profile/update
Content-Type: application/json

{
  "name": "Dakejon",
  "surname": "Nurlanovic"
}